### ISSUE TITLE
Outgoing TCP connection timeout 

### ISSUE THREAD

**Issue by RichardPar** [geneb/tcpser#1]
Hi there,

The outgoing connections currently don't timeout.I forked your codebase and added in the feature. Currently at 5 seconds.  

I tried to make a branch on your codebase but for some reason I got permission denied. 

https://github.com/RichardPar/tcpser

Richard

**Comment by geneb** [comment]
Richard, you should check out FozzTex's fork of tcpser here: https://github.com/FozzTexx/tcpser - his has more recent updates & fixes.
g.
